- platform: template
  sensors:
    solar_status:
      friendly_name: "Solar Status"
      value_template: >-
        {% if   is_state('sensor.solar_status_raw',     '0') %}  Standby: initializing
        {% elif is_state('sensor.solar_status_raw',     '1') %}  Standby: detecting insulation resistance
        {% elif is_state('sensor.solar_status_raw',     '3') %}  Standby: grid detecting
        {% elif is_state('sensor.solar_status_raw',   '256') %}  Starting
        {% elif is_state('sensor.solar_status_raw',   '512') %}  On-grid
        {% elif is_state('sensor.solar_status_raw',   '513') %}  Grid Connection: power limited
        {% elif is_state('sensor.solar_status_raw',   '514') %}  Grid Connection: self-derating
        {% elif is_state('sensor.solar_status_raw',   '768') %}  Shutdown: fault
        {% elif is_state('sensor.solar_status_raw',   '769') %}  Shutdown: command
        {% elif is_state('sensor.solar_status_raw',   '770') %}  Shutdown: OVGR
        {% elif is_state('sensor.solar_status_raw',   '771') %}  Shutdown: communication disconnected
        {% elif is_state('sensor.solar_status_raw',   '772') %}  Shutdown: power limited
        {% elif is_state('sensor.solar_status_raw',   '773') %}  Shutdown: manual startup required
        {% elif is_state('sensor.solar_status_raw',   '774') %}  Shutdown: DC switches disconnected
        {% elif is_state('sensor.solar_status_raw',   '775') %}  Shutdown: rapid cutoff
        {% elif is_state('sensor.solar_status_raw',   '776') %}  Shutdown: input underpowered
        {% elif is_state('sensor.solar_status_raw',  '1025') %}  Grid scheduling: cosphi-P curve
        {% elif is_state('sensor.solar_status_raw',  '1026') %}  Grid scheduling: Q-U curve
        {% elif is_state('sensor.solar_status_raw',  '1027') %}  Grid scheduling: dry contact
        {% elif is_state('sensor.solar_status_raw',  '1028') %}  Grid scheduling: Q-P curve
        {% elif is_state('sensor.solar_status_raw',  '1280') %}  Spot-check ready
        {% elif is_state('sensor.solar_status_raw',  '1281') %}  Spot-checking
        {% elif is_state('sensor.solar_status_raw',  '1536') %}  Inspecting
        {% elif is_state('sensor.solar_status_raw',  '1792') %}  AFCI self check
        {% elif is_state('sensor.solar_status_raw',  '2048') %}  I-V scanning
        {% elif is_state('sensor.solar_status_raw',  '2304') %}  DC input detection
        {% elif is_state('sensor.solar_status_raw',  '2560') %}  Running: off-grid charging
        {% elif is_state('sensor.solar_status_raw', '40960') %}  Standby: no irradiation
        {% else %}
          Failed to read sensor
        {% endif %}
# weather
- platform: template
  sensors:
    dark_outside:
      unique_id: 05836502-ee80-4449-8c97-6f20350c6642
      friendly_name: "Is it Dark outside"
      value_template: >-
        {% if (states.sun.sun.attributes.elevation | int < 5) %}
          true
        {% elif (is_state('weather.home', 'cloudy')) %}
          true
        {% elif ( (states.sun.sun.attributes.elevation | int < 15) and (is_state('weather.home', 'partlycloudy')) ) %}
          true
        {% else %} 
          false
        {% endif %}
