#===================================
#===================================
#=== MQTT sensors
#===================================
# licznik1 (energia pobrana z sieci)
- platform: mqtt
  name: "licznik1_licznik_koniec_dnia_stan"
  state_topic: "energia/licznik1/dzien/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik1/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik1_licznik_koniec_dnia_data_raportu"
  state_topic: "energia/licznik1/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik1_licznik_zuzycie_wczoraj_mqtt"
  state_topic: "energia/licznik1/dzien/wczoraj/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik1_licznik_koniec_mca_stan"
  state_topic: "energia/licznik1/mc/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik1/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik1_licznik_koniec_mca_data_raportu"
  state_topic: "energia/licznik1/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik1_licznik_zuzycie_poprzedni_miesiac_mqtt"
  state_topic: "energia/licznik1/mc/poprzedni/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik1_licznik_koniec_roku_stan"
  state_topic: "energia/licznik1/rok/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik1/rok/timestamp_raportu"
- platform: mqtt
  name: "licznik1_licznik_koniec_roku_data_raportu"
  state_topic: "energia/licznik1/rok/timestamp_raportu"
# licznik2 (energia oddana do sieci)
- platform: mqtt
  name: "licznik2_licznik_koniec_dnia_stan"
  state_topic: "energia/licznik2/dzien/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik2/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik2_licznik_koniec_dnia_data_raportu"
  state_topic: "energia/licznik2/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik2_licznik_zuzycie_wczoraj_mqtt"
  state_topic: "energia/licznik2/dzien/wczoraj/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik2_licznik_koniec_mca_stan"
  state_topic: "energia/licznik2/mc/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik2/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik2_licznik_koniec_mca_data_raportu"
  state_topic: "energia/licznik2/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik2_licznik_zuzycie_poprzedni_miesiac_mqtt"
  state_topic: "energia/licznik2/mc/poprzedni/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik2_licznik_koniec_roku_stan"
  state_topic: "energia/licznik2/rok/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik2/rok/timestamp_raportu"
- platform: mqtt
  name: "licznik2_licznik_koniec_roku_data_raportu"
  state_topic: "energia/licznik2/rok/timestamp_raportu"
# licznik3 (energia wytworzona przez panele PV)
- platform: mqtt
  name: "licznik3_licznik_koniec_dnia_stan"
  state_topic: "energia/licznik3/dzien/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik3/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik3_licznik_koniec_dnia_data_raportu"
  state_topic: "energia/licznik3/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik3_licznik_zuzycie_wczoraj_mqtt"
  state_topic: "energia/licznik3/dzien/wczoraj/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik3_licznik_koniec_mca_stan"
  state_topic: "energia/licznik3/mc/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik3/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik3_licznik_koniec_mca_data_raportu"
  state_topic: "energia/licznik3/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik3_licznik_zuzycie_poprzedni_miesiac_mqtt"
  state_topic: "energia/licznik3/mc/poprzedni/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik3_licznik_koniec_roku_stan"
  state_topic: "energia/licznik3/rok/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik3/rok/timestamp_raportu"
- platform: mqtt
  name: "licznik3_licznik_koniec_roku_data_raportu"
  state_topic: "energia/licznik3/rok/timestamp_raportu"
# licznik4 (zuzycie domowe)
- platform: mqtt
  name: "licznik4_licznik_koniec_dnia_stan"
  state_topic: "energia/licznik4/dzien/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik4/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik4_licznik_koniec_dnia_data_raportu"
  state_topic: "energia/licznik4/dzien/timestamp_raportu"
- platform: mqtt
  name: "licznik4_licznik_zuzycie_wczoraj_mqtt"
  state_topic: "energia/licznik4/dzien/wczoraj/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik4_licznik_koniec_mca_stan"
  state_topic: "energia/licznik4/mc/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik4/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik4_licznik_koniec_mca_data_raportu"
  state_topic: "energia/licznik4/mc/timestamp_raportu"
- platform: mqtt
  name: "licznik4_licznik_zuzycie_poprzedni_miesiac_mqtt"
  state_topic: "energia/licznik4/mc/poprzedni/stan"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "licznik4_licznik_koniec_roku_stan"
  state_topic: "energia/licznik4/rok/stan"
  unit_of_measurement: "kWh"
  json_attributes_topic: "energia/licznik4/rok/timestamp_raportu"
- platform: mqtt
  name: "licznik4_licznik_koniec_roku_data_raportu"
  state_topic: "energia/licznik4/rok/timestamp_raportu"
